---
- name: Deploy Hello World Application
  hosts: localhost
  connection: local
  
  tasks:
    - name: Manage Kubernetes Namespace
      kubernetes.core.k8s:
        state: "{{ cluster_state | default('present') }}"
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ target_namespace | default('default') }}"
            
    - name: Manage Hello World Deployment
      kubernetes.core.k8s:
        state: "{{ cluster_state | default('present') }}"
        namespace: "{{ target_namespace | default('default') }}"
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: hello-world
            spec:
            replicas: "{{ pod_count | default(5) | int }}"
            selector:
              matchLabels:
                app: hello-world
            template:
              metadata:
                labels:
                  app: hello-world
              spec:
                containers:
                  - name: hello-world
                    image: "{{ image_name | default('nginx') }}"
                    ports: "{{ [ {'containerPort': app_port | default(80) | int} ] }}"
                    
    - name: Create NodePort Service
      kubernetes.core.k8s:
        state: "{{ cluster_state | default('present') }}"
        namespace: "{{ target_namespace | default('default') }}"
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: hello-world-service
          spec:
            type: NodePort
            selector:
              app: hello-world
            ports: "{{ [ {'port': 80, 'targetPort': app_port | default(80) | int} ] }}"
